keywords = [
    "Xây Dựng Tin Học",
    "Khoa Học Thông Tin",
    "Quản Trị CNTT",
    "Kiến Trúc CNTT",
    "Trực Tuyến",
    "Online",
    "Mã QR",
    "Mở Cửa",
    "Tin Học Hóa",
    "Tự Động Hóa",
    "Số Hóa",
    "Thông Minh",
    "Bối Cảnh",
    "Nhắn Tin Tức Thời",
    "Trí Tuệ Nhân Tạo",
    "5G",
    "Hệ Thống Thông Tin",
    "An Ninh Thông Tin",
    "Mở Kết Nối",
    "Liên Kết",
    "Chia Sẻ",
    "Thực Tế Ảo",
    "Hệ Thống Không Gian Mạng Vật Lý",
    "Công Nghệ Tài Chính",
    "Trí Tuệ Nhân Tạo",
    "Nhận Diện Khuôn Mặt",
    "Face ID",
    "Giám Sát Thời Gian Thực",
    "Xác Thực Vân Tay",
    "eKYC",
    "Học Sâu",
    "Machine Learning",
    "Thiết Bị Đeo Thông Minh",
    "Máy Học",
    "Quét Khuôn Mặt",
    "Dấu Giọng",
    "Nhận Diện Giọng Nói Thông Minh",
    "Nhận Diện Sinh Trắc Học",
    "Xác Thực Sinh Trắc Học",
    "Khai Phá Văn Bản",
    "Tính Toán Mô Phỏng Não",
    "Biểu Diễn Ảnh",
    "Xử Lý Ngôn Ngữ Tự Nhiên",
    "Chuỗi Khối",
    "Blockchain"
    "Chuỗi Liên Minh",
    "Tính Toán An Toàn Nhiều Bên",
    "Tính Toán Phân Tán",
    "Điện Toán Đám Mây",
    "Cung Cấp Dịch Vụ Đám Mây",
    "Đám Mây Tài Chính",
    "Kiến Trúc Điện Toán Đám Mây",
    "Hạ Tầng Dưới Dạng Dịch Vụ",
    "Nền Tảng Dưới Dạng Dịch Vụ",
    "Phần Mềm Dưới Dạng Dịch Vụ",
    "Dữ Liệu Lớn",
    "Khai Phá Dữ Liệu",
    "Dòng Dữ Liệu",
    "Tập Dữ Liệu",
    "Khai Phá Thông Tin",
    "Quản Trị Quan Hệ Khách Hàng",
    "Internet",
    "Điện Thoại Di Động",
    "Di Động",
    "Thiết Bị Di Động",
    "Mạng",
    "Từ Xa",
    "Điện Tử",
    "API ",
    "Internet Vạn Vật",
    "IoT ",
    "Truyền Thông Di Động",
    "Tài Chính Internet",
    "Sinh Thái Số",
    "Ngân Hàng Mở",
    "Ngân Hàng Trực Tuyến",
    "Ngân Hàng Điện Tử",
    "E-Banking",
    "Ngân Hàng Internet",
    "Ngân Hàng Di Động",
    "Ví Điện Tử",
    "Ngân Hàng WeChat",
    "Thiết Bị Tự Phục Vụ",
    "Tài Chính Điện Tử",
    "Ngân Hàng Thông Minh",
    "Sản Phẩm Tài Chính Trực Tuyến",
    "VTM",
    "Thương Mại Điện Tử",
    "E-Commerce",
    "Ngân Hàng Internet Mở",
    "Kết Nối Hệ Thống Mở",
    "Ngân Hàng Số",
    "Ngân Hàng Số 1",
    "Ngân Hàng Số Một",
    "Chuỗi Cung Ứng Trực Tuyến",
    "Bán Lẻ Thông Minh",
    "Smart Sell",
    "Thương Mại Không Tiếp Xúc",
    "Tài Chính Tình Huống & Thanh Toán Bên Thứ Ba",
    "Thanh Toán Di Động",
    "Thanh Toán Trực Tuyến",
    "Thanh Toán Qua Mạng",
    "Thanh Toán Bằng Điện Thoại",
    "Thanh Toán NFC",
    "Tiền Tệ Số",
    "Thanh Toán Điện Tử",
    "Thanh Toán Mã Vạch",
    "Thanh Toán qua Mã QR",
    "Thanh Toán Mã QR",
    "Dữ Liệu Lưu Trữ Lớp EB",
    "Thanh Toán Thiết Bị Đeo",
    "Thanh Toán Không Cảm Biến",
    "Cho Vay Ngang Hàng",
    "Cho Vay P2P",
    "Gọi Vốn Cộng Đồng",
    "Cho Vay Qua Internet",
    "Tài Trợ Mạng",
    "Đầu Tư Trực Tuyến",
    "Gọi Vốn Cổ Phần Hóa",
    "Hệ Thống Hỗ Trợ Ra Quyết Định Đầu Tư",
    "Tài Trợ Trực Tuyến",
    "Tài Chính Toàn Diện",
    "Định Giá Cá Nhân Hóa",
    "Tài Trợ Theo Bối Cảnh",
    "Tài Chính Tiêu Dùng",
    "Quản Lý Tài Sản Trực Tuyến",
    "Bảo Hiểm Trực Tuyến",
    "Tài Chính Tự Động",
    "Cố Vấn Chuyên Gia",
    "Cố Vấn Thông Minh",
    "Tín Dụng Dữ Liệu Lớn",
    "Kiểm Soát Rủi Ro Dữ Liệu Lớn",
    "Fintech"
]
